trigger:
  branches:
    include:
      - feature/agro-dev
      - dev
      - qa

  tags:
    include:
      - feature/s2u-dev
      - dev
      - qa

resources:
  repositories:
    - repository: templates
      type: git
      name: EIAP_DevOps/pep-eiap-potato-sourcing-matrix-pipeline-templates
      ref: master

variables:
  - template: variables.yaml@templates
  - name: appname
    value: potato-sourcing-matrix-api-repo

stages:
  - template: Spring-CICD.yaml@templates
    parameters:
      isPython: true
      isUI: false
      isfortifyScanRequired: true
      isSonarScanRequired: false
      isSnykScanRequired: true
